# Generated by Django 5.2.16 on 2026-07-08 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_or_email', models.CharField(max_length=255)),
                ('otp_code', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PAAIS Academy', max_length=100)),
                ('site_description', models.TextField(default='Learn the AI tools that do your everyday work')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('site_favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('primary_color', models.CharField(default='#0A0A33', max_length=7)),
                ('secondary_color', models.CharField(default='#E900FF', max_length=7)),
                ('accent_color', models.CharField(default='#2EE6D6', max_length=7)),
                ('support_email', models.EmailField(default='support@paaisacademy.com', max_length=254)),
                ('whatsapp_group', models.CharField(blank=True, max_length=255)),
                ('enable_paystack', models.BooleanField(default=True)),
                ('enable_ai_features', models.BooleanField(default=True)),
                ('enable_marketplace', models.BooleanField(default=True)),
                ('enable_certificates', models.BooleanField(default=True)),
                ('footer_text', models.TextField(default='© 2026 Pan African AI Summits & Corporate Training Ltd (PACT)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('function', models.CharField(choices=[('marketing', 'Marketing & Communications'), ('sales', 'Sales & Business Development'), ('finance', 'Finance & Accounting'), ('hr', 'Human Resources'), ('operations', 'Operations & Supply Chain'), ('customer_service', 'Customer Service'), ('founder', 'Founder / SME Owner')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pitch', models.TextField(help_text='Short marketing pitch for the track')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='track_icons/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='track_covers/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lesson_new', 'New Lesson'), ('track_complete', 'Track Completion'), ('certificate_earned', 'Certificate Earned'), ('marketplace_match', 'Job Match'), ('general', 'General')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('starter', 'Starter'), ('practitioner', 'Practitioner'), ('champion', 'Champion')], default='starter', max_length=20)),
                ('duration_minutes', models.IntegerField(default=20, help_text='Estimated duration in minutes')),
                ('content_html', models.TextField(help_text='Rich HTML content')),
                ('video_url', models.URLField(blank=True, help_text='Optional embedded video')),
                ('objectives', models.JSONField(default=list, help_text='Array of learning objectives')),
                ('sample_prompt', models.TextField(blank=True, help_text='Example AI prompt for this lesson')),
                ('ai_tools_covered', models.JSONField(default=list, help_text='Tools covered: ChatGPT, Claude, Perplexity, etc.')),
                ('quiz_questions', models.JSONField(default=list, help_text='Quiz questions for this lesson')),
                ('order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.track')),
            ],
            options={
                'ordering': ['track', 'level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(choices=[('starter', 'AI Starter'), ('practitioner', 'AI Practitioner'), ('champion', 'AI Champion')], max_length=20)),
                ('credential_number', models.CharField(max_length=50, unique=True)),
                ('badge_image', models.ImageField(blank=True, null=True, upload_to='badges/')),
                ('is_verified', models.BooleanField(default=True)),
                ('verification_code', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('public_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.track')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('item_type', models.CharField(max_length=50)),
                ('item_id', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('paystack_reference', models.CharField(blank=True, max_length=100)),
                ('paystack_authorization_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('business_function', models.CharField(blank=True, choices=[('marketing', 'Marketing & Communications'), ('sales', 'Sales & Business Development'), ('finance', 'Finance & Accounting'), ('hr', 'Human Resources'), ('operations', 'Operations & Supply Chain'), ('customer_service', 'Customer Service'), ('founder', 'Founder / SME Owner')], max_length=50)),
                ('country', models.CharField(blank=True, choices=[('gh', 'Ghana'), ('ng', 'Nigeria'), ('ke', 'Kenya'), ('za', 'South Africa'), ('rw', 'Rwanda'), ('ci', "Côte d'Ivoire"), ('sn', 'Senegal'), ('uk', 'United Kingdom'), ('other', 'Other')], max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('email_notifications', models.BooleanField(default=True)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active_learner', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.track')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='started', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('quiz_score', models.IntegerField(blank=True, null=True)),
                ('quiz_passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='TrackCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('starter', 'Starter'), ('practitioner', 'Practitioner'), ('champion', 'Champion')], max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.certificate')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='core.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'track', 'level')},
            },
        ),
    ]
